app:
  name: start
strings:
  ru:
    start_message: 'Добро пожаловать! Чтобы найти игроков, пишите "+3" в канал "Поиск
      игроков": это означает, что вы ищете еще 3 игроков для матча. Другие люди будут
      писать "+2", "+1", "+0" - это означает, что они присоединяются к вам в поиске,
      и нужны соответственно еще 2 игрока, 1 игрок и так далее.


      Пожалуйста, не пишите в "Поиск игроков" ничего, кроме плюсов и чисел: этот канал
      создан для уведомлений на телефон. Заядлые игроки глушат все субканалы, кроме
      этого. Если вы поставили плюс, вас услышали. Остальное пишите в "Щас приду"
      или "Помойку".


      1. Правила: https://t.me/armelloru/10822

      2. Наш Дискорд: https://discord.gg/npnbUXG6cK

      3. Как использовать Дискорд без VPNов и прочих неудобностей: https://t.me/armelloru/5051/10130

      4. Инструкция по использованию бота для подсчета рейтинга: https://t.me/armelloru/5051/13522

      5. Как правильно играть в Армелло: руководство для тех, у кого меньше 1000 часов
      в игре https://steamcommunity.com/sharedfiles/filedetails/?id=2440672984'

    admin_granted: Вы получили права администратора
    admin_grant_failed: Вам отказано в правах администратора
    hello_message_prompt: Введите новое приветственное сообщение
    hello_message_updated: Приветственное сообщение обновлено
    hello_message_error: Ошибка при изменении приветственного сообщения
